//#define HAVE_POLL
//#define AMQ_PLATFORM "linux"
#include "amqp_consumer.c"
#include "amqp_connection.c"
#include "amqp_api.c"
#include "amqp_framing.c"
#include "amqp_socket.c"
//#include "amqp_openssl_hostname_validation.c"
//#include "amqp_openssl.c"
//#include "amqp_openssl_bio.c"
#include "amqp_mem.c"
#include "amqp_hostcheck.c"
#include "amqp_url.c"
#include "amqp_time.c"
#include "amqp_tcp_socket.c"
#include "amqp_table.c"
